// Code generated by github.com/vndocker/encrypted-graphql, DO NOT EDIT.

package model

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

func (User) IsEntity() {}
