// Code generated by github.com/vndocker/encrypted-graphql, DO NOT EDIT.

package model

import (
	"github.com/vndocker/encrypted-graphql/example/scalars/external"
)

type Address struct {
	ID       external.ObjectID `json:"id"`
	Location *Point            `json:"location"`
}
